server:
  context-path: /
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: Bot
  messages:
    basename: messages/messages
    encoding: UTF-8
  jpa:
    database: mysql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbabbbot_database
    username: root
    password: root
    hikari:
      maximum-pool-size: 15
logging:
  path: ./log


